/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedTecnicoRouteRouteImport } from './routes/_authenticated/tecnico/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedClienteRouteRouteImport } from './routes/_authenticated/cliente/route'
import { Route as AuthenticatedTecnicoIndexRouteImport } from './routes/_authenticated/tecnico/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedClienteIndexRouteImport } from './routes/_authenticated/cliente/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedTecnicoTicketsIndexRouteImport } from './routes/_authenticated/tecnico/tickets/index'
import { Route as AuthenticatedTecnicoPerfilIndexRouteImport } from './routes/_authenticated/tecnico/perfil/index'
import { Route as AuthenticatedTecnicoDispositivosIndexRouteImport } from './routes/_authenticated/tecnico/dispositivos/index'
import { Route as AuthenticatedTecnicoClientesIndexRouteImport } from './routes/_authenticated/tecnico/clientes/index'
import { Route as AuthenticatedTecnicoCatalogoIndexRouteImport } from './routes/_authenticated/tecnico/catalogo/index'
import { Route as AuthenticatedClienteTicketsIndexRouteImport } from './routes/_authenticated/cliente/tickets/index'
import { Route as AuthenticatedClientePerfilIndexRouteImport } from './routes/_authenticated/cliente/perfil/index'
import { Route as AuthenticatedClientePagoFallidoIndexRouteImport } from './routes/_authenticated/cliente/pago-fallido/index'
import { Route as AuthenticatedClientePagoExitosoIndexRouteImport } from './routes/_authenticated/cliente/pago-exitoso/index'
import { Route as AuthenticatedClienteDispositivosIndexRouteImport } from './routes/_authenticated/cliente/dispositivos/index'
import { Route as AuthenticatedTecnicoTicketsTicketIdRouteImport } from './routes/_authenticated/tecnico/tickets/$ticketId'
import { Route as AuthenticatedTecnicoClientesClienteIdRouteImport } from './routes/_authenticated/tecnico/clientes/$clienteId'
import { Route as AuthenticatedClienteTicketsTicketIdRouteImport } from './routes/_authenticated/cliente/tickets/$ticketId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTecnicoRouteRoute =
  AuthenticatedTecnicoRouteRouteImport.update({
    id: '/tecnico',
    path: '/tecnico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteRouteRoute =
  AuthenticatedClienteRouteRouteImport.update({
    id: '/cliente',
    path: '/cliente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTecnicoIndexRoute =
  AuthenticatedTecnicoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTecnicoRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteIndexRoute =
  AuthenticatedClienteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTecnicoTicketsIndexRoute =
  AuthenticatedTecnicoTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedTecnicoRouteRoute,
  } as any)
const AuthenticatedTecnicoPerfilIndexRoute =
  AuthenticatedTecnicoPerfilIndexRouteImport.update({
    id: '/perfil/',
    path: '/perfil/',
    getParentRoute: () => AuthenticatedTecnicoRouteRoute,
  } as any)
const AuthenticatedTecnicoDispositivosIndexRoute =
  AuthenticatedTecnicoDispositivosIndexRouteImport.update({
    id: '/dispositivos/',
    path: '/dispositivos/',
    getParentRoute: () => AuthenticatedTecnicoRouteRoute,
  } as any)
const AuthenticatedTecnicoClientesIndexRoute =
  AuthenticatedTecnicoClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedTecnicoRouteRoute,
  } as any)
const AuthenticatedTecnicoCatalogoIndexRoute =
  AuthenticatedTecnicoCatalogoIndexRouteImport.update({
    id: '/catalogo/',
    path: '/catalogo/',
    getParentRoute: () => AuthenticatedTecnicoRouteRoute,
  } as any)
const AuthenticatedClienteTicketsIndexRoute =
  AuthenticatedClienteTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClientePerfilIndexRoute =
  AuthenticatedClientePerfilIndexRouteImport.update({
    id: '/perfil/',
    path: '/perfil/',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClientePagoFallidoIndexRoute =
  AuthenticatedClientePagoFallidoIndexRouteImport.update({
    id: '/pago-fallido/',
    path: '/pago-fallido/',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClientePagoExitosoIndexRoute =
  AuthenticatedClientePagoExitosoIndexRouteImport.update({
    id: '/pago-exitoso/',
    path: '/pago-exitoso/',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteDispositivosIndexRoute =
  AuthenticatedClienteDispositivosIndexRouteImport.update({
    id: '/dispositivos/',
    path: '/dispositivos/',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedTecnicoTicketsTicketIdRoute =
  AuthenticatedTecnicoTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedTecnicoRouteRoute,
  } as any)
const AuthenticatedTecnicoClientesClienteIdRoute =
  AuthenticatedTecnicoClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => AuthenticatedTecnicoRouteRoute,
  } as any)
const AuthenticatedClienteTicketsTicketIdRoute =
  AuthenticatedClienteTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/cliente': typeof AuthenticatedClienteRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/tecnico': typeof AuthenticatedTecnicoRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/cliente/': typeof AuthenticatedClienteIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tecnico/': typeof AuthenticatedTecnicoIndexRoute
  '/cliente/tickets/$ticketId': typeof AuthenticatedClienteTicketsTicketIdRoute
  '/tecnico/clientes/$clienteId': typeof AuthenticatedTecnicoClientesClienteIdRoute
  '/tecnico/tickets/$ticketId': typeof AuthenticatedTecnicoTicketsTicketIdRoute
  '/cliente/dispositivos/': typeof AuthenticatedClienteDispositivosIndexRoute
  '/cliente/pago-exitoso/': typeof AuthenticatedClientePagoExitosoIndexRoute
  '/cliente/pago-fallido/': typeof AuthenticatedClientePagoFallidoIndexRoute
  '/cliente/perfil/': typeof AuthenticatedClientePerfilIndexRoute
  '/cliente/tickets/': typeof AuthenticatedClienteTicketsIndexRoute
  '/tecnico/catalogo/': typeof AuthenticatedTecnicoCatalogoIndexRoute
  '/tecnico/clientes/': typeof AuthenticatedTecnicoClientesIndexRoute
  '/tecnico/dispositivos/': typeof AuthenticatedTecnicoDispositivosIndexRoute
  '/tecnico/perfil/': typeof AuthenticatedTecnicoPerfilIndexRoute
  '/tecnico/tickets/': typeof AuthenticatedTecnicoTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/cliente': typeof AuthenticatedClienteIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tecnico': typeof AuthenticatedTecnicoIndexRoute
  '/cliente/tickets/$ticketId': typeof AuthenticatedClienteTicketsTicketIdRoute
  '/tecnico/clientes/$clienteId': typeof AuthenticatedTecnicoClientesClienteIdRoute
  '/tecnico/tickets/$ticketId': typeof AuthenticatedTecnicoTicketsTicketIdRoute
  '/cliente/dispositivos': typeof AuthenticatedClienteDispositivosIndexRoute
  '/cliente/pago-exitoso': typeof AuthenticatedClientePagoExitosoIndexRoute
  '/cliente/pago-fallido': typeof AuthenticatedClientePagoFallidoIndexRoute
  '/cliente/perfil': typeof AuthenticatedClientePerfilIndexRoute
  '/cliente/tickets': typeof AuthenticatedClienteTicketsIndexRoute
  '/tecnico/catalogo': typeof AuthenticatedTecnicoCatalogoIndexRoute
  '/tecnico/clientes': typeof AuthenticatedTecnicoClientesIndexRoute
  '/tecnico/dispositivos': typeof AuthenticatedTecnicoDispositivosIndexRoute
  '/tecnico/perfil': typeof AuthenticatedTecnicoPerfilIndexRoute
  '/tecnico/tickets': typeof AuthenticatedTecnicoTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/cliente': typeof AuthenticatedClienteRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/tecnico': typeof AuthenticatedTecnicoRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/cliente/': typeof AuthenticatedClienteIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tecnico/': typeof AuthenticatedTecnicoIndexRoute
  '/_authenticated/cliente/tickets/$ticketId': typeof AuthenticatedClienteTicketsTicketIdRoute
  '/_authenticated/tecnico/clientes/$clienteId': typeof AuthenticatedTecnicoClientesClienteIdRoute
  '/_authenticated/tecnico/tickets/$ticketId': typeof AuthenticatedTecnicoTicketsTicketIdRoute
  '/_authenticated/cliente/dispositivos/': typeof AuthenticatedClienteDispositivosIndexRoute
  '/_authenticated/cliente/pago-exitoso/': typeof AuthenticatedClientePagoExitosoIndexRoute
  '/_authenticated/cliente/pago-fallido/': typeof AuthenticatedClientePagoFallidoIndexRoute
  '/_authenticated/cliente/perfil/': typeof AuthenticatedClientePerfilIndexRoute
  '/_authenticated/cliente/tickets/': typeof AuthenticatedClienteTicketsIndexRoute
  '/_authenticated/tecnico/catalogo/': typeof AuthenticatedTecnicoCatalogoIndexRoute
  '/_authenticated/tecnico/clientes/': typeof AuthenticatedTecnicoClientesIndexRoute
  '/_authenticated/tecnico/dispositivos/': typeof AuthenticatedTecnicoDispositivosIndexRoute
  '/_authenticated/tecnico/perfil/': typeof AuthenticatedTecnicoPerfilIndexRoute
  '/_authenticated/tecnico/tickets/': typeof AuthenticatedTecnicoTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/settings'
    | '/tecnico'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/cliente/'
    | '/help-center/'
    | '/settings/'
    | '/tecnico/'
    | '/cliente/tickets/$ticketId'
    | '/tecnico/clientes/$clienteId'
    | '/tecnico/tickets/$ticketId'
    | '/cliente/dispositivos/'
    | '/cliente/pago-exitoso/'
    | '/cliente/pago-fallido/'
    | '/cliente/perfil/'
    | '/cliente/tickets/'
    | '/tecnico/catalogo/'
    | '/tecnico/clientes/'
    | '/tecnico/dispositivos/'
    | '/tecnico/perfil/'
    | '/tecnico/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/cliente'
    | '/help-center'
    | '/settings'
    | '/tecnico'
    | '/cliente/tickets/$ticketId'
    | '/tecnico/clientes/$clienteId'
    | '/tecnico/tickets/$ticketId'
    | '/cliente/dispositivos'
    | '/cliente/pago-exitoso'
    | '/cliente/pago-fallido'
    | '/cliente/perfil'
    | '/cliente/tickets'
    | '/tecnico/catalogo'
    | '/tecnico/clientes'
    | '/tecnico/dispositivos'
    | '/tecnico/perfil'
    | '/tecnico/tickets'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/cliente'
    | '/_authenticated/settings'
    | '/_authenticated/tecnico'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/cliente/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tecnico/'
    | '/_authenticated/cliente/tickets/$ticketId'
    | '/_authenticated/tecnico/clientes/$clienteId'
    | '/_authenticated/tecnico/tickets/$ticketId'
    | '/_authenticated/cliente/dispositivos/'
    | '/_authenticated/cliente/pago-exitoso/'
    | '/_authenticated/cliente/pago-fallido/'
    | '/_authenticated/cliente/perfil/'
    | '/_authenticated/cliente/tickets/'
    | '/_authenticated/tecnico/catalogo/'
    | '/_authenticated/tecnico/clientes/'
    | '/_authenticated/tecnico/dispositivos/'
    | '/_authenticated/tecnico/perfil/'
    | '/_authenticated/tecnico/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tecnico': {
      id: '/_authenticated/tecnico'
      path: '/tecnico'
      fullPath: '/tecnico'
      preLoaderRoute: typeof AuthenticatedTecnicoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tecnico/': {
      id: '/_authenticated/tecnico/'
      path: '/'
      fullPath: '/tecnico/'
      preLoaderRoute: typeof AuthenticatedTecnicoIndexRouteImport
      parentRoute: typeof AuthenticatedTecnicoRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/': {
      id: '/_authenticated/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof AuthenticatedClienteIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tecnico/tickets/': {
      id: '/_authenticated/tecnico/tickets/'
      path: '/tickets'
      fullPath: '/tecnico/tickets/'
      preLoaderRoute: typeof AuthenticatedTecnicoTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedTecnicoRouteRoute
    }
    '/_authenticated/tecnico/perfil/': {
      id: '/_authenticated/tecnico/perfil/'
      path: '/perfil'
      fullPath: '/tecnico/perfil/'
      preLoaderRoute: typeof AuthenticatedTecnicoPerfilIndexRouteImport
      parentRoute: typeof AuthenticatedTecnicoRouteRoute
    }
    '/_authenticated/tecnico/dispositivos/': {
      id: '/_authenticated/tecnico/dispositivos/'
      path: '/dispositivos'
      fullPath: '/tecnico/dispositivos/'
      preLoaderRoute: typeof AuthenticatedTecnicoDispositivosIndexRouteImport
      parentRoute: typeof AuthenticatedTecnicoRouteRoute
    }
    '/_authenticated/tecnico/clientes/': {
      id: '/_authenticated/tecnico/clientes/'
      path: '/clientes'
      fullPath: '/tecnico/clientes/'
      preLoaderRoute: typeof AuthenticatedTecnicoClientesIndexRouteImport
      parentRoute: typeof AuthenticatedTecnicoRouteRoute
    }
    '/_authenticated/tecnico/catalogo/': {
      id: '/_authenticated/tecnico/catalogo/'
      path: '/catalogo'
      fullPath: '/tecnico/catalogo/'
      preLoaderRoute: typeof AuthenticatedTecnicoCatalogoIndexRouteImport
      parentRoute: typeof AuthenticatedTecnicoRouteRoute
    }
    '/_authenticated/cliente/tickets/': {
      id: '/_authenticated/cliente/tickets/'
      path: '/tickets'
      fullPath: '/cliente/tickets/'
      preLoaderRoute: typeof AuthenticatedClienteTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/perfil/': {
      id: '/_authenticated/cliente/perfil/'
      path: '/perfil'
      fullPath: '/cliente/perfil/'
      preLoaderRoute: typeof AuthenticatedClientePerfilIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/pago-fallido/': {
      id: '/_authenticated/cliente/pago-fallido/'
      path: '/pago-fallido'
      fullPath: '/cliente/pago-fallido/'
      preLoaderRoute: typeof AuthenticatedClientePagoFallidoIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/pago-exitoso/': {
      id: '/_authenticated/cliente/pago-exitoso/'
      path: '/pago-exitoso'
      fullPath: '/cliente/pago-exitoso/'
      preLoaderRoute: typeof AuthenticatedClientePagoExitosoIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/dispositivos/': {
      id: '/_authenticated/cliente/dispositivos/'
      path: '/dispositivos'
      fullPath: '/cliente/dispositivos/'
      preLoaderRoute: typeof AuthenticatedClienteDispositivosIndexRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/tecnico/tickets/$ticketId': {
      id: '/_authenticated/tecnico/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tecnico/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTecnicoTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedTecnicoRouteRoute
    }
    '/_authenticated/tecnico/clientes/$clienteId': {
      id: '/_authenticated/tecnico/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/tecnico/clientes/$clienteId'
      preLoaderRoute: typeof AuthenticatedTecnicoClientesClienteIdRouteImport
      parentRoute: typeof AuthenticatedTecnicoRouteRoute
    }
    '/_authenticated/cliente/tickets/$ticketId': {
      id: '/_authenticated/cliente/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/cliente/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedClienteTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
  }
}

interface AuthenticatedClienteRouteRouteChildren {
  AuthenticatedClienteIndexRoute: typeof AuthenticatedClienteIndexRoute
  AuthenticatedClienteTicketsTicketIdRoute: typeof AuthenticatedClienteTicketsTicketIdRoute
  AuthenticatedClienteDispositivosIndexRoute: typeof AuthenticatedClienteDispositivosIndexRoute
  AuthenticatedClientePagoExitosoIndexRoute: typeof AuthenticatedClientePagoExitosoIndexRoute
  AuthenticatedClientePagoFallidoIndexRoute: typeof AuthenticatedClientePagoFallidoIndexRoute
  AuthenticatedClientePerfilIndexRoute: typeof AuthenticatedClientePerfilIndexRoute
  AuthenticatedClienteTicketsIndexRoute: typeof AuthenticatedClienteTicketsIndexRoute
}

const AuthenticatedClienteRouteRouteChildren: AuthenticatedClienteRouteRouteChildren =
  {
    AuthenticatedClienteIndexRoute: AuthenticatedClienteIndexRoute,
    AuthenticatedClienteTicketsTicketIdRoute:
      AuthenticatedClienteTicketsTicketIdRoute,
    AuthenticatedClienteDispositivosIndexRoute:
      AuthenticatedClienteDispositivosIndexRoute,
    AuthenticatedClientePagoExitosoIndexRoute:
      AuthenticatedClientePagoExitosoIndexRoute,
    AuthenticatedClientePagoFallidoIndexRoute:
      AuthenticatedClientePagoFallidoIndexRoute,
    AuthenticatedClientePerfilIndexRoute: AuthenticatedClientePerfilIndexRoute,
    AuthenticatedClienteTicketsIndexRoute:
      AuthenticatedClienteTicketsIndexRoute,
  }

const AuthenticatedClienteRouteRouteWithChildren =
  AuthenticatedClienteRouteRoute._addFileChildren(
    AuthenticatedClienteRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedTecnicoRouteRouteChildren {
  AuthenticatedTecnicoIndexRoute: typeof AuthenticatedTecnicoIndexRoute
  AuthenticatedTecnicoClientesClienteIdRoute: typeof AuthenticatedTecnicoClientesClienteIdRoute
  AuthenticatedTecnicoTicketsTicketIdRoute: typeof AuthenticatedTecnicoTicketsTicketIdRoute
  AuthenticatedTecnicoCatalogoIndexRoute: typeof AuthenticatedTecnicoCatalogoIndexRoute
  AuthenticatedTecnicoClientesIndexRoute: typeof AuthenticatedTecnicoClientesIndexRoute
  AuthenticatedTecnicoDispositivosIndexRoute: typeof AuthenticatedTecnicoDispositivosIndexRoute
  AuthenticatedTecnicoPerfilIndexRoute: typeof AuthenticatedTecnicoPerfilIndexRoute
  AuthenticatedTecnicoTicketsIndexRoute: typeof AuthenticatedTecnicoTicketsIndexRoute
}

const AuthenticatedTecnicoRouteRouteChildren: AuthenticatedTecnicoRouteRouteChildren =
  {
    AuthenticatedTecnicoIndexRoute: AuthenticatedTecnicoIndexRoute,
    AuthenticatedTecnicoClientesClienteIdRoute:
      AuthenticatedTecnicoClientesClienteIdRoute,
    AuthenticatedTecnicoTicketsTicketIdRoute:
      AuthenticatedTecnicoTicketsTicketIdRoute,
    AuthenticatedTecnicoCatalogoIndexRoute:
      AuthenticatedTecnicoCatalogoIndexRoute,
    AuthenticatedTecnicoClientesIndexRoute:
      AuthenticatedTecnicoClientesIndexRoute,
    AuthenticatedTecnicoDispositivosIndexRoute:
      AuthenticatedTecnicoDispositivosIndexRoute,
    AuthenticatedTecnicoPerfilIndexRoute: AuthenticatedTecnicoPerfilIndexRoute,
    AuthenticatedTecnicoTicketsIndexRoute:
      AuthenticatedTecnicoTicketsIndexRoute,
  }

const AuthenticatedTecnicoRouteRouteWithChildren =
  AuthenticatedTecnicoRouteRoute._addFileChildren(
    AuthenticatedTecnicoRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClienteRouteRoute: typeof AuthenticatedClienteRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedTecnicoRouteRoute: typeof AuthenticatedTecnicoRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClienteRouteRoute: AuthenticatedClienteRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedTecnicoRouteRoute: AuthenticatedTecnicoRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
